/**
 * This file was auto-generated by swagger-to-ts.
 * Do not make direct changes to the file.
 */

export interface components {
  schemas: {
    Result: { statusCode?: number; information?: string };
    SigninDataRequestModel: { yesQuestion?: string; temperature?: number };
    SigninRequestModel: {
      signinData?: components["schemas"]["SigninDataRequestModel"];
      user?: components["schemas"]["UserRequestModel"];
    };
    UserRequestModel: { firstName?: string; lastName?: string; email?: string };
    NewUserRequestModel: {
      user?: components["schemas"]["UserRequestModel"];
      signature?: string;
      signinData?: components["schemas"]["SigninDataRequestModel"];
    };
    UserExistsResult: {
      statusCode?: number;
      information?: string;
      userExists?: boolean;
    };
    UpdateMaxCapacityRequestModel: { maxCapacity?: number };
    PinValidationRequestModel: { pin?: string };
    UserListResponse: { users: [components["schemas"]["UserRequestModel"]]}
  };
}
